# WARNING: Turning this on, will IRREVERSIBLY ERASE all worlds specified in "WorldsToRegenerate"!
Enabled: false

# Whether to disable this plugin after the worlds have been re-generated.
DisableAfterRegeneration: false

# What worlds you want to re-generate on startup.
# Comment / uncomment lines as needed.
WorldsToRegenerate:
- world
- world_nether
- world_the_end
